### ISSUE TITLE
app谜之报错

### ISSUE THREAD

**Issue by suikastar** [wgllss/WXDynamicPlugin#16]
E  FATAL EXCEPTION: main
                                                                                                    Process: com.wgllss.dynamic.host.sample, PID: 22244
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wgllss.dynamic.host.sample/com.wgllss.dynamic.ui.HomeActivity}: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@d0d4b90
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4001)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4154)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:99)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2599)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:224)
                                                                                                    	at android.os.Looper.loop(Looper.java:318)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8719)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
                                                                                                    Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@d0d4b90
                                                                                                    Caused by: java.lang.IllegalArgumentException: The style on this component requires your app theme to be Theme.AppCompat (or a descendant).
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkTheme(SourceFile:18)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkAppCompatTheme(SourceFile:5)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.checkCompatibleTheme(SourceFile:50)
                                                                                                    	at com.google.android.material.internal.ThemeEnforcement.obtainTintedStyledAttributes(SourceFile:1)
                                                                                                    	at com.google.android.material.navigation.NavigationBarView.<init>(SourceFile:5)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(SourceFile:4)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(SourceFile:3)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(SourceFile:2)
                                                                                                    	at com.google.android.material.bottomnavigation.BottomNavigationView.<init>(SourceFile:1)
                                                                                                    	at com.wgllss.dynamic.sample.feature_startup.startup.GenerateHomeLayout.syncCreateHomeNavigationLayout(GenerateHomeLayout.kt:65)
                                                                                                    	at com.wgllss.dynamic.sample.feature_startup.startup.InitHomeFirstInitializeHelp$initCreate$1$2.invokeSuspend(InitHomeFirstInitializeHelp.kt:32)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(SourceFile:12)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(SourceFile:129)
                                                                                                    	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(SourceFile:4)
                                                                                                    	at kotlinx.coroutines.scheduling.TaskImpl.run(SourceFile:3)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(SourceFile:1)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(SourceFile:15)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(SourceFile:29)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(SourceFile:1)

![QQ截图20241203225448](https://github.com/user-attachments/assets/4a1320a7-2488-43fa-bbcc-66fcb12c9cad)

刚下的源码，就加了句 workingDirPath=E\:\\android-sdk-windows\\build-tools\\33.0.0\\ 其他什么都没动
首次编译安装到手机打开后，报了这个错误，后面几次打开就复现不了了，原因不明

**Comment by suikastar** [comment]
loading_1000里面的HomeActivity继承自Activity，问题是不是出在这里？

**Comment by wgllss** [comment]
> loading_1000里面的HomeActivity继承自Activity，问题是不是出在这里？

我这边没有这问题，你自己改下打包，弄过去试试，我这边也努力复现这个问题，抓住了第一时间修复它

**Comment by suikastar** [comment]
@wgllss 请教一下，如果classloader已经加载过loading_1000里的HomeActivity了，classes_home_dex下载好了之后，classloader会重新加载classes_home_dex里的HomeActivity吗？

**Comment by suikastar** [comment]
@wgllss 没事了，看了源码，是通过key来对自定义classloader进行排重，加载classes_loading_dex和classes_home_dex用的classloader的key都是main_loading_dex_key，所以classes_home_dex下载好后，加载过classes_loading_dex的classloader会被卸载，被新的classloader替换，当打开HomeActivity时，自然就定位到classes_home_dex里的HomeActivity了。

**Comment by suikastar** [comment]
感觉不是这个插件框架的问题，像是手机系统bug或者Android Studio编译出了啥问题，现在我都复现不出来了。
