### ISSUE TITLE
启动直接崩溃

### ISSUE THREAD

**Issue by gslovemy** [wgllss/WXDynamicPlugin#9]
35:47.784 27269-27269 AndroidRuntime          com.wgllss.dynamic.host.sample       E  FATAL EXCEPTION: main
                                                                                                    Process: com.wgllss.dynamic.host.sample, PID: 27269
                                                                                                    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wgllss.dynamic.host.sample/com.wgllss.dynamic.ui.HomeActivity}: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@e53bc28
                                                                                                    	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4065)
                                                                                                    	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252)
                                                                                                    	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149)
                                                                                                    	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                                                    	at android.os.Looper.loop(Looper.java:219)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8673)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109)
                                                                                                    Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@e53bc28
                                                                                                    Caused by: java.lang.NullPointerException: clazz must not be null
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:37)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31)
                                                                                                    	at com.wgllss.dynamic.sample.feature_startup.startup.GenerateHomeLayout.syncCreateHomeFragmentLayout(GenerateHomeLayout.kt:133)
                                                                                                    	at com.wgllss.dynamic.sample.feature_startup.startup.InitHomeFirstInitializeHelp$initCreate$1$5.invokeSuspend(InitHomeFirstInitializeHelp.kt:41)
                                                                                                    	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
                                                                                                    	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
                                                                                                    	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
---------------------------- PROCESS ENDED (27269) for package com.wgllss.dynamic.host.sample ----------------------------

顺带问问，怎么添加微信

**Comment by wgllss** [comment]
项目Readme 下面有 VX

**Comment by wgllss** [comment]
> 35:47.784 27269-27269 AndroidRuntime com.wgllss.dynamic.host.sample E FATAL EXCEPTION: main Process: com.wgllss.dynamic.host.sample, PID: 27269 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.wgllss.dynamic.host.sample/com.wgllss.dynamic.ui.HomeActivity}: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@e53bc28 at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4065) at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4252) at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:91) at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:149) at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:103) at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2618) at android.os.Handler.dispatchMessage(Handler.java:110) at android.os.Looper.loop(Looper.java:219) at android.app.ActivityThread.main(ActivityThread.java:8673) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:513) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1109) Caused by: kotlinx.coroutines.JobCancellationException: Parent job is Cancelling; job=StandaloneCoroutine{Cancelling}@e53bc28 Caused by: java.lang.NullPointerException: clazz must not be null at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:37) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.host.lib.runtime.ContainerClassLoader.loadClass(ContainerClassLoader.kt:31) at com.wgllss.dynamic.sample.feature_startup.startup.GenerateHomeLayout.syncCreateHomeFragmentLayout(GenerateHomeLayout.kt:133) at com.wgllss.dynamic.sample.feature_startup.startup.InitHomeFirstInitializeHelp$initCreate$1$5.invokeSuspend(InitHomeFirstInitializeHelp.kt:41) at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33) at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106) at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:738) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678) at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665) ---------------------------- PROCESS ENDED (27269) for package com.wgllss.dynamic.host.sample ----------------------------
> 
> 顺带问问，怎么添加微信

改问题已经修复 ,不是框架上的bug, app-lib 工程里面遗漏了 配置 ，  implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
